apiVersion: v1
kind: Service
metadata:
  labels:
    app: testdeploy
  name: websvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32001
  selector:
    app: testdeploy
  type: NodePort
