apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testdeploy
  name: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: username
          mountPath: /data/username
        - name: pass
          mountPath: /data/pass
      volumes:
      - name: username
        configMap:
          name: username
      - name: pass
        configMap:
          name: pass
     
