apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "0.2"
            memory: "128M"
          
