apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
- ../base/
- pod.yaml
namespace: qa
commonLabels:
  env: qa
nameSuffix: -qa  
patchesStrategicMerge:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: username
  behavior: merge
  literals:
  - username=admin-qa
- name: pass
  behavior: merge
  files:
  - username.pass

